package hotelpms.common.config;

import hotelpms.common.role.repository.RoleRepository;
import hotelpms.common.user.entity.User;
import hotelpms.common.user.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.security.SecureRandom;
import java.util.Base64;

@Slf4j
@Component
@RequiredArgsConstructor
public class SeedDataInitializer implements ApplicationRunner {

    private final UserRepository userRepository;
    private final RoleRepository roleRepository;
    private final PasswordEncoder passwordEncoder;

    @Value("${app.seed.admin-email:admin@hotel.local}")
    private String adminEmail;

    /** Supply via ADMIN_INITIAL_PASSWORD env var. If absent, a secure random password is generated and logged once. */
    @Value("${ADMIN_INITIAL_PASSWORD:#{null}}")
    private String adminInitialPassword;

    @Override
    @Transactional
    public void run(ApplicationArguments args) {
        if (userRepository.existsByEmail(adminEmail)) {
            return;
        }

        var adminRole = roleRepository.findByName("ADMIN")
                .orElseThrow(() -> new IllegalStateException(
                        "ADMIN role not found — run Flyway migrations first"));

        boolean autoGenerated = (adminInitialPassword == null || adminInitialPassword.isBlank());
        String password = autoGenerated ? generateSecurePassword() : adminInitialPassword;

        var admin = new User();
        admin.setUsername("admin");
        admin.setFullName("System Admin");
        admin.setEmail(adminEmail);
        admin.setPasswordHash(passwordEncoder.encode(password));
        admin.setActive(true);
        admin.setRole(adminRole);
        admin.setDepartment("Management");

        userRepository.save(admin);

        if (autoGenerated) {
            log.warn("==========================================================");
            log.warn("  Admin user created with a generated password.");
            log.warn("  Email:    {}", adminEmail);
            log.warn("  Password: {}", password);
            log.warn("  Change this immediately via PATCH /admin/users.");
            log.warn("  Set ADMIN_INITIAL_PASSWORD env var to suppress this.");
            log.warn("==========================================================");
        } else {
            log.info("Default admin user created: {}", adminEmail);
        }
    }

    private String generateSecurePassword() {
        byte[] bytes = new byte[18]; // 144 bits → 24 Base64 chars
        new SecureRandom().nextBytes(bytes);
        return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);
    }
}
